name: metal
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - blas=1.0=mkl
  - icc_rt=2019.0.0=h0cc432a_1
  - intel-openmp=2019.4=245
  - joblib=0.14.1=py_0
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - liblapack=3.8.0=14_mkl
  - libxgboost=0.90=1
  - lightgbm=2.3.0=py36h6538335_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mkl=2019.4=245
  - mkl-service=2.3.0=py36hfa6e2cd_0
  - msys2-conda-epoch=20160418=1
  - pip=19.3.1=py36_0
  - py-xgboost=0.90=py36_1
  - python=3.6.7=he025d50_1006
  - setuptools=42.0.2=py36_0
  - six=1.13.0=py36_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wheel=0.33.6=py36_0
  - wincertstore=0.2=py36_1003
  - pip:
    - appnope==0.1.0
    - attrs==19.3.0
    - backcall==0.1.0
    - bleach==3.1.0
    - colorama==0.4.3
    - cycler==0.10.0
    - decorator==4.4.1
    - defusedxml==0.6.0
    - dill==0.3.1.1
    - empyrical==0.5.3
    - entrypoints==0.3
    - fastscript==0.1.2
    - hyperparameter-hunter==3.0.0
    - importlib-metadata==1.3.0
    - ipdb==0.12.3
    - ipykernel==5.1.3
    - ipython==7.9.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.15.2
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==5.3.4
    - jupyter-console==6.0.0
    - jupyter-core==4.6.1
    - kiwisolver==1.1.0
    - llvmlite==0.31.0
    - lxml==4.4.2
    - markupsafe==1.1.1
    - matplotlib==3.1.2
    - mistune==0.8.4
    - mlfinlab==0.5.0
    - more-itertools==8.0.2
    - nbconvert==5.6.1
    - nbdev==0.2.3
    - nbformat==4.4.0
    - notebook==6.0.2
    - numba==0.47.0
    - numexpr==2.7.1
    - packaging==19.2
    - pandas==0.23.4
    - pandas-datareader==0.8.1
    - pandocfilters==1.4.2
    - parso==0.5.2
    - path==13.1.0
    - path-py==12.4.0
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - pip-autoremove==0.9.1
    - prometheus-client==0.7.1
    - prompt-toolkit==2.0.10
    - ptyprocess==0.6.0
    - pyfolio==0.9.2
    - pygments==2.5.2
    - pyparsing==2.4.6
    - pyrsistent==0.15.6
    - python-dateutil==2.8.1
    - pytz==2019.3
    - pywin32==227
    - pywinpty==0.5.7
    - pyyaml==5.2
    - pyzmq==18.1.1
    - qtconsole==4.6.0
    - scikit-learn==0.22.1
    - scikit-optimize==0.5.2
    - seaborn==0.9.0
    - send2trash==1.5.0
    - simplejson==3.17.0
    - tables==3.6.1
    - terminado==0.8.3
    - testpath==0.4.4
    - timeseriescv==0.2
    - tornado==6.0.3
    - traitlets==4.3.3
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - wrapt==1.11.2
    - zipp==0.6.0
prefix: C:\Users\doda\Anaconda3\envs\metal

